### ISSUE TITLE
 WARNING [django.request] Bad Request: /upload/

### ISSUE THREAD

**Issue by fjycomes** [center-for-threat-informed-defense/tram#206] opened 2023-11-06 08:03 UTC
If you have any good suggestions, I would greatly appreciate it.

[
<img width="837" alt="1ffe546053219b0cc9353bba0740734" src="https://github.com/center-for-threat-informed-defense/tram/assets/108787470/ef796f77-1d64-4aa1-bd4f-c232cd05f495">
](url)

**Comment by mehaase** [comment] 2023-11-06 13:55
Closing: duplicate of #205

**Closed by mehaase** 2023-11-06 13:55 UTC
